"""empty message

Revision ID: f83cfcf706b2
Revises: 
Create Date: 2021-03-20 00:22:15.402129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83cfcf706b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('properties_location_key', 'properties', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('properties_location_key', 'properties', ['location'])
    # ### end Alembic commands ###
